version: "3.9"
services:
  jserver:
    build:
      context: ""
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
    links:
      - "postgres"
    ports:
      - "9099:8080"
  postgres:
    image: postgres:12.6-alpine
    restart: always
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"