version: "3.1"
services:
  jserver:
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    depends_on:
      - "postgres"
      - "minio"
    links:
      - "postgres"
      - "minio"
    ports:
      - "9099:8080"
  postgres:
    image: postgres:12.6-alpine
    restart: always
    environment:
      POSTGRES_DB: "javaserver"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
#    volumes:
#      - ./minio/data:/data
#      - ./minio/log:/var/log
    environment:
      MINIO_ACCESS_KEY: javaserver_minio_access_key
      MINIO_SECRET_KEY: javaserver_minio_super_duper_secret_key
      MINIO_HTTP_TRACE: /var/log/minio.log
    command: server /data