insert into users(email,
                  first_name,
                  last_name,
                  patronymic,
                  login,
                  password,
                  phone,
                  role,
                  study_group_id)
values ('email.com',
        'Антон',
        'Мамакин',
        'Сергеевич',
        'user1',
        'user1',
        '001',
        0,
        (SELECT id FROM study_groups WHERE short_name LIKE 'ИВТ'));

insert into users(email,
                  first_name,
                  last_name,
                  patronymic,
                  login,
                  password,
                  phone,
                  role,
                  study_group_id)
values ('email1.com',
        'Павел',
        'Астуков',
        'Николаевич',
        'user2',
        'user2',
        '002',
        0,
        (SELECT id FROM study_groups WHERE short_name LIKE 'ИВТ'));

insert into users(email,
                  first_name,
                  last_name,
                  patronymic,
                  login,
                  password,
                  phone,
                  role,
                  study_group_id)
values ('email1.com',
        'Алексей',
        'Шишикин',
        '',
        'user3',
        'user3',
        '003',
        0,
        (SELECT id FROM study_groups WHERE short_name LIKE 'ИВТ'));