/*создание 3 студентов группы ИВТ факультета  ФИСТ*/
insert into users(email,
                  first_name,
                  last_name,
                  patronymic,
                  login,
                  password,
                  phone,
                  role,
                  study_group_id)
values ('anton@email.com',
        'Антон',
        'Мамакин',
        'Сергеевич',
        'user1',
        'user1',
        '001',
        0,
        (SELECT id FROM study_groups WHERE short_name LIKE 'ИВТАПбд-31'));

insert into users(email,
                  first_name,
                  last_name,
                  patronymic,
                  login,
                  password,
                  phone,
                  role,
                  study_group_id)
values ('pavel@email1.com',
        'Павел',
        'Астуков',
        'Николаевич',
        'user2',
        'user2',
        '002',
        0,
        (SELECT id FROM study_groups WHERE short_name LIKE 'ИВТАПбд-31'));

insert into users(email,
                  first_name,
                  last_name,
                  patronymic,
                  login,
                  password,
                  phone,
                  role,
                  study_group_id)
values ('alex@email2.com',
        'Алексей',
        'Шишикин',
        '',
        'user3',
        'user3',
        '003',
        0,
        (SELECT id FROM study_groups WHERE short_name LIKE 'ИВТАПбд-31'));
/*создание 3 студентов группы РТ факультета  РТФ*/
insert into users(email,
                  first_name,
                  last_name,
                  patronymic,
                  login,
                  password,
                  phone,
                  role,
                  study_group_id)
values ('tanya@email4.com',
        'Татьяна',
        'Яровова',
        'Серьгеевна',
        'user4',
        'user4',
        '004',
        0,
        (SELECT id FROM study_groups WHERE short_name LIKE 'РТбд-31'));

insert into users(email,
                  first_name,
                  last_name,
                  patronymic,
                  login,
                  password,
                  phone,
                  role,
                  study_group_id)
values ('damir@email5.com',
        'Дамир',
        'Саитов',
        '',
        'user5',
        'user5',
        '005',
        0,
        (SELECT id FROM study_groups WHERE short_name LIKE 'РТбд-31'));

insert into users(email,
                  first_name,
                  last_name,
                  patronymic,
                  login,
                  password,
                  phone,
                  role,
                  study_group_id)
values ('misha@email6.com',
        'Михаил',
        'Соловьев',
        '',
        'user6',
        'user6',
        '006',
        0,
        (SELECT id FROM study_groups WHERE short_name LIKE 'РТбд-31'));

/*создание 3 студентов группы ИНЯЗ факультета  ГМ*/

insert into users(email,
                  first_name,
                  last_name,
                  patronymic,
                  login,
                  password,
                  phone,
                  role,
                  study_group_id)
values ('nastya@email7.com',
        'Анастасия',
        'Кузнецова',
        'Серьгеевна',
        'user7',
        'user7',
        '007',
        0,
        (SELECT id FROM study_groups WHERE short_name LIKE 'ГМУбд-11'));

insert into users(email,
                  first_name,
                  last_name,
                  patronymic,
                  login,
                  password,
                  phone,
                  role,
                  study_group_id)
values ('jenya@email8.com',
        'Евгения',
        'Чернова',
        '',
        'user8',
        'user8',
        '007',
        0,
        (SELECT id FROM study_groups WHERE short_name LIKE 'ГМУбд-11'));
insert into users(email,
                  first_name,
                  last_name,
                  patronymic,
                  login,
                  password,
                  phone,
                  role,
                  study_group_id)
values ('sasha@email9.com',
        'Александра',
        'Белова',
        'Владимировна',
        'user9',
        'user9',
        '008',
        0,
        (SELECT id FROM study_groups WHERE short_name LIKE 'ГМУбд-11'));

